### ISSUE TITLE
Custom identifiers for readouts are not (no longer) working

### ISSUE THREAD

**Issue by tmadlener** [AIDASoft/DD4hep#1193]
The following readout uses a `TiledLayerGridXY` but redfines the identifiers for `x`, `y` and `z` to `I`, `J` and `K` respectively via the corresponding properties of the `TiledLayerGridXY`.

```xml
  <readout name="HBUCollection">
      <segmentation type="TiledLayerGridXY" grid_size_x="3" grid_size_y="3" offset_x="-Calo_dim_x/2.0" offset_y="-Calo_dim_y/2.0" identifier_x="I" identifier_y="J" identifier_layer="K"/>
      <id>system:8,K:8,I:8,J:8</id>
  </readout>
```

However, trying to use this in the attached geometry setup (taken from `k4geo` where also the necessary [`CaloPrototype_v01`](https://github.com/key4hep/k4geo/blob/master/detector/CaloTB/CaloPrototype_v01.cpp) lives) leads to the following error:

```
Myphysics        INFO  Registered Geant4 physics constructor G4StepLimiterPhysics to physics list
UserInitialization INFO  +++ Executing Geant4UserActionInitialization::Build. Context:0x559d425b74d0 Kernel:0x559d41ed0b90 [-1]
Geant4Converter  INFO  +++  Successfully converted geometry to Geant4.
IDDescriptor     ERROR dd4hep: HBUCollection: This ID descriptor has no field with the name: layer
Traceback (most recent call last):
  File "/home/tmadlener/work/.spack/spackages/dd4hep/master/skylake-ubuntu22.04-gcc12.3.0/krv6r6c/bin/ddsim", line 25, in <module>
    RUNNER.run()
  File "/home/tmadlener/work/.spack/spackages/dd4hep/master/skylake-ubuntu22.04-gcc12.3.0/krv6r6c/lib/python3.10/site-packages/DDSim/DD4hepSimulation.py", line 490, in run
    kernel.initialize()
cppyy.gbl.std.runtime_error: int dd4hep::sim::Geant4Kernel::initialize() =>
    runtime_error: IDDescriptor: dd4hep: HBUCollection: This ID descriptor has no field with the name: layer
```

To reproduce this it should be enough to run
```bash
ddsim -G --gun.particle pi+ --gun.position 0,0,-1000 -N 10 --compactFile MainTestBeamSetup.xml --outputFile test.slcio
```

This has apparently worked approximately two years ago but doesn't any longer. I can reproduce the issue with v01-16 und v01-11-02, so if something has changed it would have have to be been before that.

I have also tried to debug this, but I haven't gotten too far, so any insights would be greatly appreciated.

----
Geometry files
[Materials_v01.xml.txt](https://github.com/AIDASoft/DD4hep/files/13511348/Materials_v01.xml.txt)
[MainTestBeamSetup.xml.txt](https://github.com/AIDASoft/DD4hep/files/13511356/MainTestBeamSetup.xml.txt)
[TestBeamSetup_HBU.xml.txt](https://github.com/AIDASoft/DD4hep/files/13511358/TestBeamSetup_HBU.xml.txt)

**Comment by andresailer** [comment]
Most likely this change in the driver makes this fail now

https://github.com/key4hep/k4geo/commit/27d8c0ac9f145ab08fb46c6eac4d1e16331830d8#diff-6393d231778cd9b548bf48db0b6b0aedf8141b0ba44e81801967e501813c2c51R148

**Comment by andresailer** [comment]
I am going to consider this issue resolved.
