### ISSUE TITLE
k4geo CI failing, potentially caused by last DD4hep PR

### ISSUE THREAD

**Issue by atolosadelgado** [AIDASoft/DD4hep#1292]
### Check duplicate issues.

- [X] Checked for duplicates

### Goal

Hi,

The k4geo repository stores the geometry of detectors for future colliders. I noticed that CI failed with nightlies over the weekend:
https://github.com/key4hep/k4geo/actions/runs/9834053300/job/27145226265

I suspect about one of the last PR, https://github.com/AIDASoft/DD4hep/pull/1288

Please, let us know if we can provide further information that could be useful to solve the issue.

### Operating System and Version

Alma9

### compiler

GCC 11.4

### ROOT Version

6.30/06

### DD4hep Version

master

### Reproducer

the following steps will reproduce the error, in Alma9 (or Ubuntu22)

```
source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
git clone https://github.com/key4hep/k4geo.git
cd k4geo/
cmake -B build -S . -D CMAKE_INSTALL_PREFIX=install
cmake --build build -j 4 --target install
k4_local_repo
cd build
ctest -V -R t_test_steeringFile
```

The error message is the following:
```
13: Traceback (most recent call last):
13:   File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-07-08/x86_64-almalinux9-gcc11.4.1-opt/dd4hep/fe64884cac492f18574a8e2af37560667f7f3802_develop-6pb2jj/bin/ddsim", line 25, in <module>
13:     sys.exit(RUNNER.run())
13:   File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-07-08/x86_64-almalinux9-gcc11.4.1-opt/dd4hep/fe64884cac492f18574a8e2af37560667f7f3802_develop-6pb2jj/lib/python3.10/site-packages/DDSim/DD4hepSimulation.py", line 494, in run
13:     self.__setupSensitiveDetectors(detectors, function, defFilter, defAction, abort)
13:   File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-07-08/x86_64-almalinux9-gcc11.4.1-opt/dd4hep/fe64884cac492f18574a8e2af37560667f7f3802_develop-6pb2jj/lib/python3.10/site-packages/DDSim/DD4hepSimulation.py", line 652, in __setupSensitiveDetectors
13:     seq, act = setupFunction(det, action)
13:   File "/cvmfs/sw-nightlies.hsf.org/key4hep/releases/2024-07-08/x86_64-almalinux9-gcc11.4.1-opt/dd4hep/fe64884cac492f18574a8e2af37560667f7f3802_develop-6pb2jj/lib/python3.10/site-packages/DDG4.py", line 684, in setupCalorimeter
13:     elif typ is not None and self.sensitive_types.get(typ):
13: TypeError: unhashable type: 'dict'
13: corrupted size vs. prev_size in fastbins
13:  *** Break *** abort
```

**Comment by MarkusFrankATcernch** [comment]
@atolosadelgado If I look in : https://github.com/key4hep/k4geo/actions/runs/10053270118 , I suppose this issue can be closed. Correct ?

**Comment by jmcarcell** [comment]
Yes, it can be closed now
