### ISSUE TITLE
Units backwards compatibility not working

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#354]
Eveything is OK with ROOT 6.12 but with 6.08 the backwards compatibility of units does not work

```bash
ddsim  --compactFile=/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/lcgeo/HEAD/CLIC/compact/CLIC_o3_v14/CLIC_o3_v14.xml --runType=batch -G -N=100 --outputFile=testCLIC_o3_v14.slcio --gun.isotrop=true --steeringFile=/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/ClicPerformance/HEAD/examples/clic_steer.py'
DEPRECATION WARNING  The namespace "SystemOfUnits" is deprecated. Please use "g4units" instead.
WARNING: No units from TGeoUnit can be imported. This is normal for ROOT < 6.12.0
Traceback (most recent call last):
  File "/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/lcgeo/HEAD/bin/ddsim", line 16, in <module>
    RUNNER.run()
  File "/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/lcgeo/HEAD/lib/python/DDSim/DD4hepSimulation.py", line 282, in run
    import DDG4, DD4hep
  File "/cvmfs/clicdp.cern.ch/software/ROOT/6.08.00/x86_64-slc6-gcc62-opt/lib/ROOT.py", line 303, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc62-opt/DD4hep/HEAD/python/DDG4.py", line 64, in <module>
    from   dd4hep_base import TGeoUnits
ImportError: cannot import name TGeoUnits
```

**Comment by petricm** [comment]
We can totally drop the g4units/System of units since Geant4 has a python units file here

https://github.com/Geant4/geant4/blob/master/environments/g4py/source/python/hepunit.py
