### ISSUE TITLE
Bug: PseudoTrap with negative radius

### ISSUE THREAD

**Issue by ianna** [AIDASoft/DD4hep#449]
Union is fine:
```
    <PseudoTrap name="ptrap1" dx1="10*cm" dx2="3*cm" dy1="30*cm" dy2="10*cm" dz="30*cm" radius="10*cm" atMinusZ="false"/>
```
Intersection gives a problem:
```
    <PseudoTrap name="ptrap2" dx1="10*cm" dx2="3*cm" dy1="30*cm" dy2="10*cm" dz="30*cm" radius="-10*cm" atMinusZ="true"/>

```

```
#4  <signal handler called>
#5  0x00007fa387e5c9c6 in cms::DDNamespace::addSolidNS(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::Solid_type<TGeoShape>) const () from /build/yana/DD4HEP/CMSSW_10_4_X_2018-10-17-2300/lib/slc6_amd64_gcc700/libDetectorDescriptionDDCMS.so
#6  0x00007fa387e5cc6f in cms::DDNamespace::addSolid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::Solid_type<TGeoShape>) const () from /build/yana/DD4HEP/CMSSW_10_4_X_2018-10-17-2300/lib/slc6_amd64_gcc700/libDetectorDescriptionDDCMS.so
#7  0x00007fa386a08c80 in dd4hep::Converter<dd4hep::(anonymous namespace)::SolidSection, dd4hep::xml::Handle_t>::operator()(dd4hep::xml::Handle_t) const () from /build/yana/DD4HEP/CMSSW_10_4_X_2018-10-17-2300/lib/slc6_amd64_gcc700/libDetectorDescriptionDD4HepPlugins.so
#8  0x00007fa386a0ebef in load_dddefinition(dd4hep::Detector&, dd4hep::xml::Handle_t) () from /build/yana/DD4HEP/CMSSW_10_4_X_2018-10-17-2300/lib/slc6_amd64_gcc700/libDetectorDescriptionDD4HepPlugins.so
#9  0x00007fa386a10d0e in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::xml_document_DDDefinition, long (dd4hep::Detector*, dd4hep::xml::Handle_t*)>::call(dd4hep::Detector*, dd4hep::xml::Handle_t*) () from /build/yana/DD4HEP/CMSSW_10_4_X_2018-10-17-2300/lib/slc6_amd64_gcc700/libDetectorDescriptionDD4HepPlugins.so
#10 0x00007fa387b45772 in dd4hep::DetectorLoad::processXMLElement(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::xml::Handle_t const&) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-17-2300/external/slc6_amd64_gcc700/lib/libDDCore.so.1.8
#11 0x00007fa387b45cd0 in dd4hep::DetectorLoad::processXML(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::xml::UriReader*) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-17-2300/external/slc6_amd64_gcc700/lib/libDDCore.so.1.8
#12 0x00007fa387b37ccd in dd4hep::DetectorImp::fromXML(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, dd4hep::DetectorBuildType) [clone .localalias.189] () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-17-2300/external/slc6_amd64_gcc700/lib/libDDCore.so.1.8
#13 0x00007fa386aa5182 in (anonymous namespace)::Factory<dd4hep::(anonymous namespace)::DD4hep_CompactLoader, long (dd4hep::Detector*, int, char**)>::call(dd4hep::Detector*, int, char**) () from /cvmfs/cms-ib.cern.ch/week0/slc6_amd64_gcc700/cms/cmssw/CMSSW_10_4_X_2018-10-17-2300/external/slc6_amd64_gcc700/lib/libDDCorePlugins.so
```
Example:
https://cmssdt.cern.ch/lxr/source/SimG4Core/Geometry/src/DDG4SolidConverter.cc#0362

**Comment by ianna** [comment]
Confirm, it is fixed. Thanks!
