### ISSUE TITLE
DDRec.py broken

### ISSUE THREAD

**Issue by rete** [AIDASoft/DD4hep#607]
- OS version: SLC6
 - Compiler version: GCC 8.2
 - DD4hep version: v01-11, iLCSoft version v02-01-pre from Desy AFS (testing phase)
 - Goal: Running the calibration software LCCalibration
 - Python version: 2.7.16

## Issue

I can't import `DDRec.py` correctly anymore.

Minimal broken example to reproduce the issue (on a SL6 machine) :

```shell
source /afs/desy.de/project/ilcsoft/sw/x86_64_gcc82_sl6/v02-01-pre/init_ilcsoft.sh
python
```
then in python:

```python
import ROOT
from ROOT import gROOT
gROOT.SetBatch(1)

try:
    import DD4hep                   
except ImportError:
    import dd4hep as DD4hep

import DDRec
```

I get the following error on `import DDRec`:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc82_sl6/v02-01-pre/root/6.18.04/lib/ROOT.py", line 533, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc82_sl6/v02-01-pre/DD4hep/v01-11/lib/python2.7/site-packages/DDRec.py", line 101, in <module>
    std_list_ISurface = core.std_list('ISurface*')
  File "/afs/desy.de/project/ilcsoft/sw/x86_64_gcc82_sl6/v02-01-pre/root/6.18.04/lib/cppyy.py", line 130, in __call__
    result = _backend.MakeRootTemplateClass( *newargs )
SyntaxError: could not get __cppname__ from provided template argument. Is it a str, class, type or int?
```

It was working with iLCSoft v02-00-02 (production version) with DD4hep v01-07-02, as we ran our energy calibration with this version.

**Comment by andresailer** [comment]
I can confirm that this also fails with our nightly builds
```
$ source /cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc7-opt/init_ilcsoft.sh
----------------------------------------------
Build created on Wed Feb  5 04:45:16 UTC 2020
----------------------------------------------
$ python
Python 2.7.14 (default, Sep 28 2017, 12:48:29)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ROOT
>>> from ROOT import gROOT
>>> gROOT.SetBatch(1)
>>>
>>> try:
...     import DD4hep
... except ImportError:
...     import dd4hep as DD4hep
...
>>> import DDRec
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/cvmfs/clicdp.cern.ch/software/ROOT/6.12.06/x86_64-slc6-gcc7-opt/lib/ROOT.py", line 318, in _importhook
    return _orig_ihook( name, *args, **kwds )
  File "/cvmfs/clicdp.cern.ch/iLCSoft/builds/nightly/x86_64-slc6-gcc7-opt/DD4hep/HEAD/lib/python2.7/site-packages/DDRec.py", line 101, in <module>
    std_list_ISurface = core.std_list('ISurface*')
  File "/cvmfs/clicdp.cern.ch/software/ROOT/6.12.06/x86_64-slc6-gcc7-opt/lib/cppyy.py", line 130, in __call__
    result = _backend.MakeRootTemplateClass( *newargs )
SyntaxError: could not get __cppname__ from provided template argument. Is it a str, class, type or int?
>>>

```

**Comment by andresailer** [comment]
Unicode strikes again.
needs to be:
```python
    std_list_ISurface = core.std_list(str('ISurface*'))
```
