### ISSUE TITLE
ROOT 6.22 compatibility issue

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#671]
Currently there is this blocking issue upstream

https://sft.its.cern.ch/jira/browse/ROOT-10669

**Comment by petricm** [comment]
One issue with ROOT 6.22 solved but now another was uncovered. The multi collection tests fail

```
        127 - t_ClientTests_g4material_scan_MultiCollections_LONGTEST (Failed)
	158 - t_ClientTests_sim_MultiCollections (Failed)
	160 - t_ClientTests_sim_MultiSegmentCollections (Failed)
``` 

with the trace

```py
Traceback (most recent call last):
  File "/DD4hep/examples/examples/ClientTests/scripts/MultiCollections.py", line 71, in <module>
    run()
  File "/DD4hep/examples/examples/ClientTests/scripts/MultiCollections.py", line 53, in run
    seq, act = geant4.setupCalorimeter('TestCal')
  File "/DD4hep/lib/python2.7/site-packages/DDG4.py", line 630, in setupCalorimeter
    return self.setupDetector(name, type, collections)
  File "/DD4hep/lib/python2.7/site-packages/DDG4.py", line 612, in setupDetector
    act = SensitiveAction(self.kernel(), sensitive_type + '/' + coll_nam + 'Handler', name)
NotImplementedError
```

**Comment by petricm** [comment]
So the simple reproducer is
```py
import DDG4

kernel = DDG4.Kernel()
geometry = "file:" + "__PATH__/DD4hep/examples/examples/ClientTests/compact/MultiCollections.xml"
kernel.loadGeometry(str(geometry))
geant4 = DDG4.Geant4(kernel)

seq, act = geant4.setupCalorimeter('TestCal')
```
and the last line breaks.
But if you expand the `setupCalorimeter` call it is
```py
description = kernel.detectorDescription()
sd = description.sensitiveDetector(str('TestCal'))
type = 'Geant4CalorimeterAction'
```
followed by a call to `return self.setupDetector(name, type, collections)` which is
```py
seq = DDG4.SensitiveSequence(kernel, 'Geant4SensDetActionSequence/' + 'TestCal')
sd = description.sensitiveDetector(str('TestCal'))
coll_nam = 'TestCallInnerLayerHits' # or TestCallMiddleLayerHits or TestCallOuterLayerHits
act = DDG4.SensitiveAction(kernel, sensitive_type + '/' + coll_nam + 'Handler', 'TestCal')
```
and if you do this by hand it works (and it should not)... and I am lost.

One more interesting observation is that if you execute the lines below and exit python with CTRL+D you get a seg fault.
```
2020-06-05 17:14 mpetric@pclcdgpu:build (fixGuard)$ python
Python 2.7.16 (default, Apr 30 2020, 17:53:11) 
[GCC 9.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import DDG4
>>> kernel = DDG4.Kernel()
PersistencyIO    INFO  +++ Set Streamer to dd4hep::OpaqueDataBlock
Info in <TGeoManager::TGeoManager>: Geometry default, Detector Geometry created
>>> 
 *** Break *** segmentation violation
```

but only if you do call `kernel = DDG4.Kernel()`.

**Comment by petricm** [comment]
All this is tested already with inclusion of #673

**Comment by petricm** [comment]
OK resolved it was this 
```diff
+     act = SensitiveAction(self.kernel(), sensitive_type + '/' + coll_nam + 'Handler', name)
-     act = SensitiveAction(self.kernel(), sensitive_type + '/' + str(coll_nam) + 'Handler', name)
```
why this behaves differently with the new ROOT I don't know

**Comment by MarkusFrankATcernch** [comment]
Somehow the python string conversion does not work like before.
Anyhow: Fantastic work! Congratulations!
Thanks a lot!
