### ISSUE TITLE
python bindings not working on macOS with ROOT 6.22

### ISSUE THREAD

**Issue by petricm** [AIDASoft/DD4hep#700]
The simples `import dd4hep` results in
```
Error in <TInterpreter::AutoParse>: Error parsing payload code for class dd4hep::tools::Evaluator with content:

#line 1 "G__DD4hep dictionary payload"

#ifndef DD4HEP_MUST_USE_DETECTORIMP_H
  #define DD4HEP_MUST_USE_DETECTORIMP_H 1
#endif
#ifndef BOOST_SPIRIT_USE_PHOENIX_V3
  #define BOOST_SPIRIT_USE_PHOENIX_V3 1
#endif
#ifndef BOOST_SPIRIT_USE_PHOENIX_V3
  #define BOOST_SPIRIT_USE_PHOENIX_V3 1
#endif
#ifndef DD4HEP_USE_XERCESC
  #define DD4HEP_USE_XERCESC 1
#endif

.... all header files ....

#pragma link C++ class dd4hep::Detector+;

#pragma link C++ class dd4hep::detail::interp;
#pragma link C++ class dd4hep::detail::eval;

#pragma link C++ function dd4hep::run_interpreter(const string& name);
#pragma link C++ function dd4hep::_toDictionary(const string&, const string&);
#pragma link C++ function dd4hep::toStringSolid(const TGeoShape*, int);
#pragma link C++ function dd4hep::toStringMesh(const TGeoShape*, int);
#pragma link C++ function dd4hep::toStringMesh(dd4hep::PlacedVolume, int);

#include "DD4hep/ConditionsData.h"
#pragma link C++ class dd4hep::cond::ClientData+;
#pragma link C++ class dd4hep::cond::AbstractMap+;
#pragma link C++ class dd4hep::cond::AbstractMap::Params+;

#endif  // __CINT__
#endif  /* DD4HEP_DDCORE_ROOTDICTIONARY_H  */

#undef  _BACKWARD_BACKWARD_WARNING_H

Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Error in <TClass::LoadClassInfo>: no interpreter information for class dd4hep::NamedObject is available even though it has a TClass initialization routine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-mac1015-clang110-opt/lib/python3.7/site-packages/dd4hep.py", line 12, in <module>
    from dd4hep_base import *  # noqa: F403
  File "/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-mac1015-clang110-opt/lib/python3.7/site-packages/dd4hep_base.py", line 124, in <module>
    import_namespace_item('core', 'run_interpreter')
  File "/Users/Shared/cvmfs/sft.cern.ch/lcg/views/LCG_98python3/x86_64-mac1015-clang110-opt/lib/python3.7/site-packages/dd4hep_base.py", line 67, in import_namespace_item
    attr = getattr(scope, nam)
AttributeError: <namespace cppyy.gbl.dd4hep at 0x7fbd7ef99f90> has no attribute 'run_interpreter'. Full details:
  type object 'dd4hep' has no attribute 'run_interpreter'
  'dd4hep::run_interpreter' is not a known C++ class
  'run_interpreter' is not a known C++ template
  'run_interpreter' is not a known C++ enum
```

basically same problem as #632

**Comment by petricm** [comment]
Re-opened [new issue](https://sft.its.cern.ch/jira/browse/ROOT-11029) as with ROOT
