### ISSUE TITLE
listcomponents seg faults 

### ISSUE THREAD

**Issue by smuzaffar** [AIDASoft/DD4hep#782]
Hi,
  I noticed that `listcomponents` segfaults in CMSSW ASAN (address sanitizer) builds. It works fine for CMSSW normal builds but for ASAN builds it fails [a]. Looks like it is failing somewhere in ROOT code, any suggestions to get rid of this crash?

[a] https://github.com/cms-sw/cmssw/issues/32854
```
0x00007ffff7e7a2e0 in std::_Vector_base<ROOT::Internal::TSchemaHelper, std::allocator<ROOT::Internal::TSchemaHelper> >::_Vector_impl_data::_Vector_impl_data (
    this=0x7ffff0673ad0 <ROOT::GenerateInitInstanceLocal(TROOT const*)::instance+208>) at /build/muz/s/w/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:95
95              : _M_start(), _M_finish(), _M_end_of_storage()
(gdb) where
#0  0x00007ffff7e7a2e0 in std::_Vector_base<ROOT::Internal::TSchemaHelper, std::allocator<ROOT::Internal::TSchemaHelper> >::_Vector_impl_data::_Vector_impl_data (
    this=0x7ffff0673ad0 <ROOT::GenerateInitInstanceLocal(TROOT const*)::instance+208>) at /build/muz/s/w/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:95
#1  0x00007ffff043a700 in std::_Vector_base<ROOT::Internal::TSchemaHelper, std::allocator<ROOT::Internal::TSchemaHelper> >::_Vector_impl::_Vector_impl (
    this=0x7ffff0673ad0 <ROOT::GenerateInitInstanceLocal(TROOT const*)::instance+208>) at /build/muz/s/w/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:130
#2  0x00007ffff043a684 in std::_Vector_base<ROOT::Internal::TSchemaHelper, std::allocator<ROOT::Internal::TSchemaHelper> >::_Vector_base (
    this=0x7ffff0673ad0 <ROOT::GenerateInitInstanceLocal(TROOT const*)::instance+208>) at /build/muz/s/w/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:285
#3  0x00007ffff043a6a0 in std::vector<ROOT::Internal::TSchemaHelper, std::allocator<ROOT::Internal::TSchemaHelper> >::vector (this=0x7ffff0673ad0 <ROOT::GenerateInitInstanceLocal(TROOT const*)::instance+208>)
    at /build/muz/s/w/slc7_amd64_gcc900/external/gcc/9.3.0/include/c++/9.3.0/bits/stl_vector.h:484
#4  0x00007ffff04389ad in ROOT::TGenericClassInfo::TGenericClassInfo (this=0x7ffff0673a00 <ROOT::GenerateInitInstanceLocal(TROOT const*)::instance>, fullClassname=0x7ffff0541003 "TROOT", version=0,
    declFileName=0x7ffff0540ffb "TROOT.h", declFileLine=93, info=..., action=0x7ffff064aaf0 <ROOT::Internal::DefineBehavior(void*, void*)::theDefault>, dictionary=0x7ffff04c090a <TROOT::Dictionary()>, isa=0x4bfd90,
    pragmabits=16, sizof=704) at /build/muz/s/w/BUILD/slc7_amd64_gcc900/lcg/root/6.22.06-cms/root-6.22.06/core/meta/src/TGenericClassInfo.cxx:118
#5  0x00007ffff04a929b in ROOT::GenerateInitInstanceLocal () at core/G__Core.cxx:6605
#6  0x00007ffff04a937c in ROOT::GenerateInitInstance () at core/G__Core.cxx:6614
#7  0x00007ffff02fbc30 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at /build/muz/s/w/BUILD/slc7_amd64_gcc900/lcg/root/6.22.06-cms/root-6.22.06/core/base/src/TROOT.cxx:594
#8  0x00007ffff02fbc60 in _GLOBAL__sub_I_TROOT.cxx(void) () at /build/muz/s/w/BUILD/slc7_amd64_gcc900/lcg/root/6.22.06-cms/root-6.22.06/core/base/src/TROOT.cxx:3100
#9  0x00007ffff7dea9c3 in _dl_init_internal () from /lib64/ld-linux-x86-64.so.2
#10 0x00007ffff7def59e in dl_open_worker () from /lib64/ld-linux-x86-64.so.2
#11 0x00007ffff7dea7d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#12 0x00007ffff7deeb8b in _dl_open () from /lib64/ld-linux-x86-64.so.2
#13 0x00007ffff7bd7fab in dlopen_doit () from /lib64/libdl.so.2
#14 0x00007ffff7dea7d4 in _dl_catch_error () from /lib64/ld-linux-x86-64.so.2
#15 0x00007ffff7bd85ad in _dlerror_run () from /lib64/libdl.so.2
#16 0x00007ffff7bd8041 in dlopen@@GLIBC_2.2.5 () from /lib64/libdl.so.2
#17 0x0000000000409f3b in main (argc=2, argv=0x7fffffff5b68) at /build/muz/s/w/BUILD/slc7_amd64_gcc900/external/dd4hep/v01-14x-cms2/dd4hep-v01-14x/GaudiPluginService/src/listcomponents.cpp:114
```

**Comment by smuzaffar** [comment]
this issue has been understood. please see the details cms-sw/cmssw#32854 .
