### ISSUE TITLE
Stacking Action in DD4hep to kill particles

### ISSUE THREAD

**Issue by chiaramaccani** [AIDASoft/DD4hep#993]
Hello, I have a simple question. 
I would like to kill the tracking of Geant4 particles in some cases.
Is it possible for me to create a Stacking Action class, maybe inheriting from Geant4StackingAction, with a method ClassifyNewTrack (like the one implemented in Geant4) to change the status of the track depending on some conditions that I can decide? How can it then be compiled and included in the sequences.xml file?
Or are there other ways to achieve this goal?
Thank you very much.

**Comment by MarkusFrankATcernch** [comment]
Hi,
the Geant4Context allows to access the main stacking action:
Geant4SteppingActionSequence& steppingAction() const;
This function is called by Geant4.

You can here add user defined sub-classes of type `Geant4StackingAction`.
When Geant4 calls the stacking action sequence, then all attached modules of this type are called -- ie also you one.
Inside your specialized module you should be able to do what you want. You have to provide the callbacks
in your class inheriting from `Geant4StackingAction`:
```
      /// New-stage callback
      virtual void newStage() {
      }
      /// Preparation callback
      virtual void prepare() {
      }

```
These correspond to the callback of Geant4 to:
```
    class G4UserStackingAction
    {
      virtual void NewStage();
      virtual void PrepareNewEvent();
    };
```
Is this what you are looking for ?

**Comment by chiaramaccani** [comment]
Yes.
Then if I add a function ClassifyNewTrack in my inherited class will it be called by Geant4 in place of its?
And how can I include it into the sequences.xml file? What is wrong in some lines like these?

<sequence name="Geant4StackingActionSequence/StackingAction">
                <action name="MyStackingAction/MyStackingAction">
                </action>
</sequence>

(where MyStackingAction inherits from Geant4StackingAction)

**Comment by MarkusFrankATcernch** [comment]
In principle this should work with this xml setup. 
I do not spot anything wrong there and the xml parser should cope with this.
Where does it exactly fail ? Does it not find the stacking sequence or your
sub-action ?

However, please take note that the xml is deprecated....please change to python setup, there everything is simpler.

**Comment by chiaramaccani** [comment]
For now I just created a simple derived class, without adding anything, in a folder of my project ${PROJECT_DIR}/Core/include/Channeling/Geant4ChannelingStackingAction.h
`
#ifndef DDG4_GEANT4CHANNELINGSTACKING_H
#define DDG4_GEANT4CHANNELINGSTACKING_H
#include <DDG4/Geant4StackingAction.h>
    class Geant4ChannelingStackingAction: public dd4hep::sim::Geant4StackingAction {
     public:
      /// Standard constructor
      Geant4ChannelingStackingAction(dd4hep::sim::Geant4Context* context, const std::string& name);
      /// Default destructor
      ~Geant4ChannelingStackingAction();
      /// New-stage callback
      void newStage() {
      }
      /// Preparation callback
       void prepare() {
      }
    };
#endif
`


And I compiled my project adding these lines to the CMakeList.txt file:
`
add_library(ChannelingStacking SHARED
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/src/Channeling/Geant4ChannelingStackingAction.cpp
)
target_include_directories(ChannelingStacking PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Core/include/Channeling/>
)
target_link_libraries(ChannelingStacking ROOT::Core ROOT::Geom ROOT::Gdml DD4hep::DDCore DD4hep::DDCond DD4hep::DDG4)
add_library(IR3Detector::ChannelingStacking ALIAS ChannelingStacking)
`





Then if I add to the file sequences.xml the lines
`
<sequence name="Geant4StackingActionSequence/StackingAction">
        <action name="Geant4ChannelingStackingAction/ChannelingStackingAction">
        </action>
</sequence>
`


I obtain this error:
`
Geant4Setup      INFO  +++ ActionSequence StackingAction of type Geant4StackingActionSequence added.
Geant4Handle     ERROR Failed to create object of type Geant4ChannelingStackingAction!

****************************************************
*  A runtime error has occured :
*    Geant4Handle: Failed to create object of type Geant4ChannelingStackingAction!
dd4hep: Error interpreting XML nodes of type <sequence/>
dd4hep: Error interpreting XML nodes of type <sequences/>
dd4hep: while parsing /afs/cern.ch/work/c/cmaccani/ir3detector/sim/sequences.xml
dd4hep: with plugin:DD4hep_XMLLoader
*  the program will have to be terminated - sorry.
`





If I try to run with a python script adding the lines 
`
stack = DDG4.StackingAction(kernel, 'Geant4ChannelingStackingAction/ChannelingStackingAction')
kernel.generatorAction().adopt(stack)
`

I obtain this error:
`
Geant4Handle     ERROR Failed to create object of type Geant4ChannelingStackingAction!
Traceback (most recent call last):
  File "/afs/cern.ch/work/c/cmaccani/ir3detector/sim/ddg4_ir3.py", line 193, in <module>
    run(output=args.output, macro=args.macro, events=args.events)
  File "/afs/cern.ch/work/c/cmaccani/ir3detector/sim/ddg4_ir3.py", line 77, in run
    stack = DDG4.StackingAction(kernel, 'Geant4ChannelingStackingAction/ChannelingStackingAction')
  File "/afs/cern.ch/work/c/cmaccani/DD4hep/lib/python3.9/site-packages/DDG4.py", line 213, in StackingAction
    return Interface.createStackingAction(kernel, str(nam), shared)
cppyy.gbl.std.runtime_error: static dd4hep::sim::StackingActionHandle dd4hep::sim::Geant4ActionCreation::createStackingAction(dd4hep::sim::KernelHandle& kernel, const string& name_type, bool shared) =>
    runtime_error: Geant4Handle: Failed to create object of type Geant4ChannelingStackingAction!
 *** Break *** segmentation violation
`



What am I doing wrong?

**Comment by chiaramaccani** [comment]
For now I just created a simple derived class, without adding anything, in a folder ${PROJECT_DIR}/Core/include/Channeling/Geant4ChannelingStackingAction.h

```
#ifndef DDG4_GEANT4CHANNELINGSTACKING_H
#define DDG4_GEANT4CHANNELINGSTACKING_H
#include <DDG4/Geant4StackingAction.h>
    class Geant4ChannelingStackingAction: public dd4hep::sim::Geant4StackingAction {
     public:
      /// Standard constructor
      Geant4ChannelingStackingAction(dd4hep::sim::Geant4Context* context, const std::string& name);
      /// Default destructor
      ~Geant4ChannelingStackingAction();
      /// New-stage callback
      void newStage() {
      }
      /// Preparation callback
       void prepare() {
      }
    };
#endif
```


And I compiled my project adding these lines to the CMakeList.txt file:
```
add_library(ChannelingStacking SHARED
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/src/Channeling/Geant4ChannelingStackingAction.cpp
)
target_include_directories(ChannelingStacking PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/Core/include/Channeling/>
)
target_link_libraries(ChannelingStacking ROOT::Core ROOT::Geom ROOT::Gdml DD4hep::DDCore DD4hep::DDCond DD4hep::DDG4)
add_library(IR3Detector::ChannelingStacking ALIAS ChannelingStacking)
```


Then if I add to the file sequences.xml the lines
```
<sequence name="Geant4StackingActionSequence/StackingAction">
        <action name="Geant4ChannelingStackingAction/ChannelingStackingAction">
        </action>
</sequence>
```


I obtain this error:
```
Geant4Setup      INFO  +++ ActionSequence StackingAction of type Geant4StackingActionSequence added.
Geant4Handle     ERROR Failed to create object of type Geant4ChannelingStackingAction!
****************************************************
*  A runtime error has occured :
*    Geant4Handle: Failed to create object of type Geant4ChannelingStackingAction!
dd4hep: Error interpreting XML nodes of type <sequence/>
dd4hep: Error interpreting XML nodes of type <sequences/>
dd4hep: while parsing /afs/cern.ch/work/c/cmaccani/ir3detector/sim/sequences.xml
dd4hep: with plugin:DD4hep_XMLLoader
*  the program will have to be terminated - sorry.
```


If I try to run with a python script adding the lines 

```
stack = DDG4.StackingAction(kernel, 'Geant4ChannelingStackingAction/ChannelingStackingAction')
kernel.generatorAction().adopt(stack)
```

I obtain this error:
```
Geant4Handle     ERROR Failed to create object of type Geant4ChannelingStackingAction!
Traceback (most recent call last):
  File "/afs/cern.ch/work/c/cmaccani/ir3detector/sim/ddg4_ir3.py", line 193, in <module>
    run(output=args.output, macro=args.macro, events=args.events)
  File "/afs/cern.ch/work/c/cmaccani/ir3detector/sim/ddg4_ir3.py", line 77, in run
    stack = DDG4.StackingAction(kernel, 'Geant4ChannelingStackingAction/ChannelingStackingAction')
  File "/afs/cern.ch/work/c/cmaccani/DD4hep/lib/python3.9/site-packages/DDG4.py", line 213, in StackingAction
    return Interface.createStackingAction(kernel, str(nam), shared)
cppyy.gbl.std.runtime_error: static dd4hep::sim::StackingActionHandle dd4hep::sim::Geant4ActionCreation::createStackingAction(dd4hep::sim::KernelHandle& kernel, const string& name_type, bool shared) =>
    runtime_error: Geant4Handle: Failed to create object of type Geant4ChannelingStackingAction!
 *** Break *** segmentation violation
```



What am I doing wrong?

**Comment by andresailer** [comment]
instead of `add_library` you need to use `add_dd4hep_plugin`

```cmake
add_dd4hep_plugin(ChannelingStacking SHARED
  ${CMAKE_CURRENT_SOURCE_DIR}/Core/src/Channeling/Geant4ChannelingStackingAction.cpp)
```

Which will create the necessary `libChannelingStacking.components` file for the plugin manager.
And
```c++
#include <DDG4/Factories.h>
/// your class
DECLARE_GEANT4ACTION(Geant4ChannelingStackingAction)
```
in `${PROJECT_DIR}/Core/include/Channeling/Geant4ChannelingStackingAction.h`
(or some other macro? @MarkusFrankATcernch )

Then after cmake and make you should have a libChannelingStacking.components file which contains
```
v2::libChannelingStacking.so:Geant4ChannelingStackingAction
```

**Comment by MarkusFrankATcernch** [comment]
This should be all correct. The Geant4XMLSetup.cpp does the appropriate casts.
The stacking actions should not be any different in this sense as the other ones.

**Comment by chiaramaccani** [comment]
Ok thank you very much, it compiles and the class is loaded.
Now i have added a function 
```
G4ClassificationOfNewTrack ClassifyNewTrack(const G4Track* aTrack);
```
that I would like it to be called in place of the Geant4 one reported in the class [G4UserStackingAction](https://apc.u-paris.fr/~franco/g4doxy/html/classG4UserStackingAction.html), but it doesn't seem to me that Geant actually calls mine.

Is there something else I am missing?

**Comment by MarkusFrankATcernch** [comment]
Naaa. I must have overlooked the function `ClassifyNewTrack` when defining the interface, so that user callbacks are executed properly. I will have to add this to DDG4. There is nothing you can do right now.

**Comment by MarkusFrankATcernch** [comment]
I prepared a fix and a small test....waiting for the test-builds.

**Comment by MarkusFrankATcernch** [comment]
https://github.com/AIDASoft/DD4hep/pull/998

This is yours ! have a look at the example.

**Comment by chiaramaccani** [comment]
Ok it works! 
Thank you very much.

**Comment by MarkusFrankATcernch** [comment]
@chiaramaccani If you are happy, please close the issue....
